Adding models from schema
Orange-hanter/AnriProject pull request #3
Opened 2023-09-17 18:14 UTC by ivanboika

I've added all models from schema without extra changes. I remember that @132dannys task may include changes at schema as optomization process

2023-09-18 12:29 UTC, 132dannys commented on api/anri/apps/products/models/order.py
> +    user_id = models.OneToOneField("User")
user_id - >user

2023-09-25 09:21 UTC, Orange-hanter requested changes

2023-09-25 13:58 UTC, ivanboika commented on api/anri/apps/users/models/contragent.py
> +    contact_email = models.CharField(max_length=127)
Done

2023-09-25 13:58 UTC, ivanboika commented on api/anri/apps/orders/models/order_item.py
> +    quantity = models.IntegerField()
Comment fixed, where is typo I don't see

2023-09-25 13:58 UTC, ivanboika commented on api/anri/apps/carts/models/cart_item.py
> +    quantity = models.IntegerField()
Done

2023-09-25 13:58 UTC, ivanboika commented on api/anri/apps/carts/models/cart_item.py
> +    # product = models.ForeignKey("products.Product", on_delete=models.CASCADE)
Fixed

2023-09-25 14:44 UTC, Orange-hanter approved these changes

2023-09-25 16:43 UTC, Orange-hanter commented
@132dannys approve please

2023-09-25 16:45 UTC, 132dannys approved these changes

2023-09-25 16:46 UTC, merged